version: "3"

services:
  next-app:
    image: ygcrew-web
    container_name: next-app
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        - ygcrew-web
    env_file:
      - .env
    ports:
      - 3000:3000
